const varieties = [
  {
    id: 9,
    name: "Наполеон",
    color: "Желтый",
    category: "food",
    type: "Авторский",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 8,
    droughtResistance: 4,
    productivity: "Высокая",
    storage: "Средняя",
    tasteProfile: "Полусухой, сладкий, ароматный",
    desc: "Авторский сорт семьи Луцан. Получен из семян в 2020 году. Необыкновенно вкусный, сладкий, как торт \"Наполеон\". Полусухой, крахмальный с плотной мякотью.",
    rawTaste: "Напоминает вкус сырых съедобных каштанов. Мякоть плотная, хрустящая.",
    bakedTaste: "Полусухой, сладкий, ароматный. Приятный насыщенный вкус.",
    yield: "Шикарная урожайность",
    img: "napoleon.webp",
    price: "—",
    advantages: ["Ранний", "Авторский", "Патентованный", "Для новичков", "Популярный"],
    patent: true
  },
  {
    id: 10,
    name: "Окинавский",
    color: "Фиолетовый",
    category: "food",
    type: "Столовый",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 7,
    droughtResistance: 2,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "okinavskiy.webp",
    price: "Закончился",
    advantages: [],
    patent: false
  },
  {
    id: 11,
    name: "Американский бежевый",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Высокая",
    storage: "Средняя",
    tasteProfile: "Сладкий, мягкий, нежный, без волокон, полувлажный",
    desc: "Образует компактный куст с трёхзубчатым листом. Показал достойную урожайность, при сроке созревания 130 дней. Корнеплоды бежевого цвета, мякоть белая, с розоватыми вкраплениями.",
    rawTaste: "Хрустящий, умеренно сладкий, плотный, крахмалистый. Напоминает вкус сырых каштанов с молоком.",
    bakedTaste: "Сладкий, мягкий, нежный, без волокон, полувлажный.",
    img: "amerikanskiy-bezhevyy.webp",
    price: "300 руб",
    advantages: [],
    patent: false
  },
  {
    id: 12,
    name: "Афганский",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 2,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "afganskiy.webp",
    price: "500 руб",
    advantages: [],
    patent: false
  },
  {
    id: 13,
    name: "Белый НБС",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 4,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Сладкий, приятный вкус",
    desc: "Сухумский Белый",
    img: "belyy-nbs.webp",
    price: "500 руб",
    advantages: [],
    patent: false
  },
  {
    id: 14,
    name: "Ла-Баю-Белл",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 8,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "la-bayu-bell.webp",
    price: "750 руб",
    advantages: ["Для сыроедения", "Популярный"],
    patent: false
  },
  {
    id: 15,
    name: "Бали",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "bali.webp",
    price: "600 руб",
    advantages: ["Для сыроедения"],
    patent: false
  },
  {
    id: 16,
    name: "Бельву",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 4,
    droughtResistance: 4,
    productivity: "Высокая",
    storage: "Отличная",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    desc: "Сорт с оранжевой мякотью, привезенный из США. Красивые бежевые клубни. Урожайный, 100-110 дней. Отлично хранится.",
    img: "belvu.webp",
    price: "600 руб",
    advantages: [],
    patent: false
  },
  {
    id: 17,
    name: "Борегард",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 8,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Очень сладкий, насыщенный вкус",
    img: "boregard.webp",
    price: "700 руб",
    advantages: ["Для сыроедения", "Популярный"],
    patent: false
  },
  {
    id: 18,
    name: "Бэтти",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "betty.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 19,
    name: "Кумара Рэд",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "kumara-red.webp",
    price: "600 руб",
    advantages: [],
    patent: false
  },
  {
    id: 20,
    name: "Кумара",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "kumara.webp",
    price: "600 руб",
    advantages: [],
    patent: false
  },
  {
    id: 21,
    name: "Бенихарука",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 8,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "beniharuka.webp",
    price: "700 руб",
    advantages: ["Новинка"],
    patent: false
  },
  {
    id: 22,
    name: "Ковингтон",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 4,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "kovington.webp",
    price: "550 руб",
    advantages: [],
    patent: false
  },
  {
    id: 23,
    name: "Карамельный",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 8,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "karamelnyy.webp",
    price: "600 руб",
    advantages: [],
    patent: false
  },
  {
    id: 24,
    name: "Красный женьшень",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "krasnyy-zhenshen.webp",
    price: "—",
    advantages: ["Архивный"],
    patent: false
  },
  {
    id: 25,
    name: "Джуно",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 7,
    droughtResistance: 2,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "dzhuno.webp",
    price: "550 руб",
    advantages: [],
    patent: false
  },
  {
    id: 26,
    name: "Джерси",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "dzhersi.webp",
    price: "400 руб",
    advantages: ["Популярный"],
    patent: false
  },
  {
    id: 27,
    name: "Джевел",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "dzhevel.webp",
    price: "550 руб",
    advantages: ["Популярный"],
    patent: false
  },
  {
    id: 28,
    name: "Голден",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 8,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "В меру влажный, сочный, очень сладкий, вкусный",
    desc: "Средне-ранний старый сорт с мощными плетями. Мякоть светло-желтая.",
    bakedTaste: "В меру влажный, сочный, очень сладкий, вкусный.",
    img: "goldean.webp",
    price: "400 руб",
    advantages: [],
    patent: false
  },
  {
    id: 29,
    name: "Гарнет",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 4,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "garnet.webp",
    price: "—",
    advantages: ["Архивный"],
    patent: false
  },
  {
    id: 30,
    name: "Винницкий розовый",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 4,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    desc: "Редголд, Тэккен",
    img: "vinnitskiy-rozovyy.webp",
    price: "400 руб",
    advantages: ["Для новичков", "Популярный"],
    patent: false
  },
  {
    id: 31,
    name: "Венесуэльский Фиолет.",
    color: "Фиолетовый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 5,
    droughtResistance: 2,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "venesuelskiy-fioletovyy.webp",
    price: "Закончился",
    advantages: [],
    patent: false
  },
  {
    id: 32,
    name: "Вардаман",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 8,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "vardaman.webp",
    price: "600 руб",
    advantages: ["Ранний"],
    patent: false
  },
  {
    id: 33,
    name: "Бургунди",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 4,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Аромат моркови, влажный, сочный, нежный, идеален для детского прикорма",
    desc: "Новая селекция от Луизианского агроцентра. Менее влажный, с очень насыщенным вкусом.",
    rawTaste: "Сладкий, как яблоко. Твердый, хрустящий, сочный.",
    bakedTaste: "Аромат моркови, влажный, сочный, нежный, идеален для детского прикорма.",
    img: "burgundi.webp",
    price: "Закончился",
    advantages: [],
    patent: false
  },
  {
    id: 34,
    name: "Бонита",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Поздний (120+)",
    termDays: {min: 120, max: 150},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "bonita.webp",
    price: "400 руб",
    advantages: [],
    patent: false
  },
  {
    id: 35,
    name: "Бразильский",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "brazilskiy.webp",
    price: "300 руб",
    advantages: ["Популярный"],
    patent: false
  },
  {
    id: 36,
    name: "Сливочный Шаньдунский",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "slivochnyy-shandunskiy.webp",
    price: "Закончился",
    advantages: ["Ранний", "Популярный"],
    patent: false
  },
  {
    id: 37,
    name: "Сладкий №1",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "sladkiy-1.webp",
    price: "700 руб",
    advantages: [],
    patent: false
  },
  {
    id: 38,
    name: "Рубин Каролины",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "rubin-karoliny.webp",
    price: "500 руб",
    advantages: [],
    patent: false
  },
  {
    id: 39,
    name: "Рошфор",
    color: "Фиолетовый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 4,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "roshfor.webp",
    price: "700 руб",
    advantages: [],
    patent: false
  },
  {
    id: 40,
    name: "Пурпл №2",
    color: "Фиолетовый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "purpl-2.webp",
    price: "400 руб",
    advantages: [],
    patent: false
  },
  {
    id: 41,
    name: "Пурпл №1",
    color: "Фиолетовый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 3,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "purpl-1.webp",
    price: "400 руб",
    advantages: [],
    patent: false
  },
  {
    id: 42,
    name: "Порто Рико",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "porto-amarello.webp",
    price: "500 руб",
    advantages: ["Архивный"],
    patent: false
  },
  {
    id: 43,
    name: "Порто Ляранж",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "portu-baterraba.webp",
    price: "400 руб",
    advantages: ["Архивный"],
    patent: false
  },
  {
    id: 44,
    name: "Порту-Батерраба",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 3,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "portu-baterraba.webp",
    price: "400 руб",
    advantages: ["Для новичков", "Популярный"],
    patent: false
  },
  {
    id: 45,
    name: "Порто-Амарелло",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 2,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "porto-amarello.webp",
    price: "500 руб",
    advantages: [],
    patent: false
  },
  {
    id: 46,
    name: "Пестролистый",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 6,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    img: "pestrolistyy.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 47,
    name: "Победа 100",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 6,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Очень сладкий, насыщенный вкус",
    img: "pobeda-100.webp",
    price: "300 руб",
    advantages: ["Ранний", "Архивный"],
    patent: false
  },
  {
    id: 48,
    name: "Орлеанский",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "orleanskiy.webp",
    price: "500 руб",
    advantages: [],
    patent: false
  },
  {
    id: 50,
    name: "Нэнси Хол",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "",
    price: "400 руб",
    advantages: ["Архивный"],
    patent: false
  },
  {
    id: 51,
    name: "О'Генри",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 4,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "ogenri.webp",
    price: "400 руб",
    advantages: [],
    patent: false
  },
  {
    id: 52,
    name: "Мускатный",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "muskatnyy.webp",
    price: "—",
    advantages: ["Архивный"],
    patent: false
  },
  {
    id: 53,
    name: "Мохан",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "mohan.webp",
    price: "500 руб",
    advantages: [],
    patent: false
  },
  {
    id: 54,
    name: "Московский",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "moskovskiy.webp",
    price: "500 руб",
    advantages: [],
    patent: false
  },
  {
    id: 55,
    name: "Мексиканский",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 6,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "meksikanskiy.webp",
    price: "300 руб",
    advantages: ["Архивный"],
    patent: false
  },
  {
    id: 56,
    name: "Манчжурский улучш.",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "manchzhurskiy-uluchshennyy.webp",
    price: "750 руб",
    advantages: ["Ранний", "Для новичков", "Популярный"],
    patent: false
  },
  {
    id: 57,
    name: "Манчжурский",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 1,
    droughtResistance: 2,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "manchzhurskiy.webp",
    price: "750 руб",
    advantages: ["Ранний", "Для сыроедения", "Популярный"],
    patent: false
  },
  {
    id: 58,
    name: "Кумара White",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "kumara-white.webp",
    price: "600 руб",
    advantages: [],
    patent: false
  },
  {
    id: 59,
    name: "Спартак",
    color: "Оранжевый",
    category: "food",
    type: "Авторский",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 2,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "spartak.webp",
    price: "750 руб",
    advantages: ["Ранний", "Авторский"],
    patent: false
  },
  {
    id: 60,
    name: "Елисей",
    color: "Желтый",
    category: "food",
    type: "Авторский",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 2,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "elisey.webp",
    price: "750 руб",
    advantages: ["Ранний", "Авторский"],
    patent: false
  },
  {
    id: 61,
    name: "Богатырь",
    color: "Оранжевый",
    category: "food",
    type: "Авторский",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 3,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "bogatyr.webp",
    price: "750 руб",
    advantages: ["Ранний", "Авторский", "Для новичков"],
    patent: false
  },
  {
    id: 62,
    name: "Добрыня",
    color: "Оранжевый",
    category: "food",
    type: "Авторский",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 3,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "dobrynya.webp",
    price: "Закончился",
    advantages: ["Ранний", "Авторский", "Для новичков", "Популярный"],
    patent: false
  },
  {
    id: 63,
    name: "Грушевый Джем",
    color: "Оранжевый",
    category: "food",
    type: "Авторский",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    desc: "Сорт с необычным грушевым вкусом.",
    img: "grushevyy-dzhem.webp",
    price: "—",
    advantages: ["Авторский", "Для сыроедения"],
    patent: false
  },
  {
    id: 64,
    name: "Медовое Чудо",
    color: "Желтый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 10,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "medovoe-chudo.webp",
    price: "—",
    advantages: ["Авторский", "Патентованный"],
    patent: true
  },
  {
    id: 65,
    name: "Лик Ангела",
    color: "Белый",
    category: "decor",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Высокая",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    desc: "Авторский сорт Batatchudo, обильно цветёт и даёт съедобные клубни.",
    img: "lik-angela.webp",
    price: "—",
    advantages: ["Авторский"],
    patent: false
  },
  {
    id: 66,
    name: "Чилипси",
    color: "Желтый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 3,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "chilipsi.webp",
    price: "—",
    advantages: ["Авторский", "Патентованный"],
    patent: true
  },
  {
    id: 67,
    name: "ФриЧипс",
    color: "Белый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 4,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "frichips.webp",
    price: "—",
    advantages: ["Авторский"],
    patent: false
  },
  {
    id: 68,
    name: "Ральф",
    color: "Фиолетовый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "ralf.webp",
    price: "—",
    advantages: ["Авторский", "Патентованный"],
    patent: true
  },
  {
    id: 69,
    name: "О'Натали",
    color: "Белый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "onatali.webp",
    price: "—",
    advantages: ["Авторский"],
    patent: false
  },
  {
    id: 70,
    name: "О'Виталий",
    color: "Фиолетовый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "ovitaliy.webp",
    price: "—",
    advantages: ["Авторский", "Патентованный"],
    patent: true
  },
  {
    id: 71,
    name: "Луциан",
    color: "Желтый",
    category: "food",
    type: "Авторский",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "lucian.webp",
    price: "—",
    advantages: ["Авторский", "Патентованный"],
    patent: true
  },
  {
    id: 72,
    name: "Краснодарский",
    color: "Белый",
    category: "food",
    type: "Авторский",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "krasnodarskiy.webp",
    price: "—",
    advantages: ["Авторский"],
    patent: false
  },
  {
    id: 73,
    name: "Каролина 1",
    color: "Белый",
    category: "decor",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 3,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "karolina-1.webp",
    price: "—",
    advantages: ["Авторский"],
    patent: false
  },
  {
    id: 74,
    name: "Карат",
    color: "Оранжевый",
    category: "food",
    type: "Авторский",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 4,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "karat.webp",
    price: "—",
    advantages: ["Ранний", "Авторский", "Патентованный", "Для сыроедения", "Популярный"],
    patent: true
  },
  {
    id: 75,
    name: "Блик №2",
    color: "Белый",
    category: "food",
    type: "Авторский",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 7,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    desc: "Продолжаем наблюдать за сортом Блик. Явное отличие от Блик №1. На вкус потрясающе вкусные.",
    img: "blik-2.webp",
    price: "—",
    advantages: ["Авторский", "Патентованный"],
    patent: true
  },
  {
    id: 76,
    name: "Блик №1",
    color: "Белый",
    category: "food",
    type: "Авторский",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 5,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "blik-1.webp",
    price: "—",
    advantages: ["Авторский", "Патентованный"],
    patent: true
  },
  {
    id: 77,
    name: "Берёзка",
    color: "Белый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 6,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "berezka.webp",
    price: "—",
    advantages: ["Авторский"],
    patent: false
  },
  {
    id: 78,
    name: "Белоснежка",
    color: "Белый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "belosnezhka.webp",
    price: "—",
    advantages: ["Авторский"],
    patent: false
  },
  {
    id: 79,
    name: "Баунти",
    color: "Белый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "baunti.webp",
    price: "—",
    advantages: ["Авторский"],
    patent: false
  },
  {
    id: 80,
    name: "Вьетнамский",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 6,
    droughtResistance: 2,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "vetnamskiy.webp",
    price: "Закончился",
    advantages: [],
    patent: false
  },
  {
    id: 81,
    name: "U-2",
    color: "Оранжевый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "u-2.webp",
    price: "—",
    advantages: ["Авторский", "Архивный"],
    patent: false
  },
  {
    id: 82,
    name: "Cara Gold",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "cara-gold.webp",
    price: "550 руб",
    advantages: ["Для сыроедения"],
    patent: false
  },
  {
    id: 83,
    name: "Японский фиолетовый",
    color: "Фиолетовый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 7,
    droughtResistance: 2,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "yaponskiy-fioletovyy.webp",
    price: "1000 руб",
    advantages: ["Для новичков", "Популярный"],
    patent: false
  },
  {
    id: 84,
    name: "Японский (Murasaki)",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 2,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "yaponskiy.webp",
    price: "500 руб",
    advantages: [],
    patent: false
  },
  {
    id: 85,
    name: "Челентано",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 8,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "chelentano.webp",
    price: "700 руб",
    advantages: [],
    patent: false
  },
  {
    id: 86,
    name: "Хар бэй",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "har-bey.webp",
    price: "—",
    advantages: ["Архивный"],
    patent: false
  },
  {
    id: 87,
    name: "Тата Кото",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 2,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "tata-koto.webp",
    price: "1000 руб",
    advantages: [],
    patent: false
  },
  {
    id: 88,
    name: "Тайнунг-Т65",
    color: "Желтый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 4,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "tainung-t65.webp",
    price: "400 руб",
    advantages: [],
    patent: false
  },
  {
    id: 89,
    name: "Сухумский",
    color: "Белый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "suhumskiy.webp",
    price: "—",
    advantages: ["Архивный"],
    patent: false
  },
  {
    id: 90,
    name: "Столетие",
    color: "Оранжевый",
    category: "food",
    type: "Столовый",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "stoletie.webp",
    price: "400 руб",
    advantages: ["Для сыроедения"],
    patent: false
  },
  {
    id: 100,
    name: "Свит Каролайн Пурпл",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Листья насыщенного пурпурного цвета. Цветет бледно-розовыми фонариками.",
    yield: "Съедобные клубни",
    img: "sweet-caroline-purple.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 101,
    name: "Свит Каролайн Сл. Сердце",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Листья ярко-пурпурные, сердцевидной формы, длинные плети.",
    yield: "Декоративный",
    img: "sweet-caroline-sweetheart.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 102,
    name: "Свит Каролайн Лайт Грин",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Листья салатового/лаймового цвета, сильно резные.",
    yield: "Съедобные клубни",
    img: "sweet-caroline-light-green.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 103,
    name: "Свит Каролайн Бронза",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Листья красноватые, форма листа корона, компактный куст.",
    yield: "Декоративный",
    img: "sweet-caroline-bronze.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 104,
    name: "Триколор (Pink Frost)",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Листья со светло-розовой каймой и хаотичными светлыми штрихами.",
    yield: "Съедобные клубни",
    img: "tricolor.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 105,
    name: "Свит Каролайн Медь",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Листья медного оттенка, лианы до 2 м.",
    yield: "Декоративный",
    img: "sweet-caroline-copper.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 106,
    name: "Каролайн милая красная",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Листья красноватые, форма вытянутое сердце.",
    yield: "Декоративный",
    img: "caroline-sweetheart-red.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 107,
    name: "Келли Рей Вайн",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Мраморно-тёмно-фиолетовые листья с зелёными вкраплениями.",
    yield: "Съедобные клубни",
    img: "kelly-ray.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 108,
    name: "Корона",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Листья светло-зелёные/лайм, форма корона.",
    yield: "Декоративный",
    img: "korona.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 109,
    name: "Расти",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Листья пурпурного оттенка, форма — сердце с зазубринками.",
    yield: "На тестировании",
    img: "rusty.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 110,
    name: "Медуза",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Мощные длинные плети, листья сильно разрезанные — ажурный кустарник.",
    yield: "Декоративный",
    img: "meduza.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 111,
    name: "Иллюзия",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Illusion Midnight Lace. На тестировании.",
    yield: "На тестировании",
    img: "illyuziya.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 112,
    name: "Псевдо Расти",
    color: "Фиолетовый",
    category: "decor",
    type: "Декоративный",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Дает вкусные клубни, сорт на тестировании.",
    yield: "Съедобные клубни",
    img: "psevdo-rasti.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 113,
    name: "Маргарита",
    color: "Белый",
    category: "decor",
    type: "Декоративный",
    term: "поздний (140+)",
    termDays: {min: 140, max: 170},
    sweetness: 0,
    droughtResistance: 4,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "",
    desc: "Листья салатово-лаймового цвета, сердцевидной формы.",
    yield: "Декоративный",
    img: "margarita.webp",
    price: "—",
    advantages: [],
    patent: false
  },
  {
    id: 114,
    name: "Искушение",
    color: "Фиолетовый",
    category: "food",
    type: "Авторский",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "iskushenie.webp",
    price: "—",
    advantages: ["Ранний", "Авторский", "Новинка"],
    patent: false
  },
  {
    id: 115,
    name: "Кубань",
    color: "Оранжевый",
    category: "food",
    type: "Авторский",
    term: "Ранний (80-90)",
    termDays: {min: 80, max: 90},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "kuban.webp",
    price: "—",
    advantages: ["Ранний", "Авторский", "Для сыроедения", "Новинка"],
    patent: false
  },
  {
    id: 116,
    name: "Ника",
    color: "Желтый",
    category: "food",
    type: "Авторский",
    term: "Средний (100-110)",
    termDays: {min: 100, max: 110},
    sweetness: 8,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "nika.webp",
    price: "—",
    advantages: ["Авторский", "Патентованный", "Новинка"],
    patent: true
  },
  {
    id: 117,
    name: "Млечный путь",
    color: "Фиолетовый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 6,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Умеренно сладкий, мягкий вкус",
    img: "mlechnyy-put.webp",
    price: "—",
    advantages: ["Авторский", "Патентованный", "Новинка"],
    patent: true
  },
  {
    id: 300,
    name: "Корикогане",
    color: "Белый",
    category: "food",
    type: "Японская коллекция",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Нежный, кремовый, умеренно сладкий",
    img: "korikogane.webp",
    price: "—",
    advantages: ["Новинка"],
    patent: false
  },
  {
    id: 301,
    name: "Аякомачи",
    color: "Оранжевый",
    category: "food",
    type: "Японская коллекция",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Насыщенный сладкий, бататовый аромат",
    img: "ayakomachi.webp",
    price: "—",
    advantages: ["Новинка"],
    patent: false
  },
  {
    id: 302,
    name: "Анноимо",
    color: "Желтый",
    category: "food",
    type: "Японская коллекция",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Насыщенный сладкий, японская селекция",
    img: "annoimo.webp",
    price: "—",
    advantages: ["Новинка"],
    patent: false
  },
  {
    id: 303,
    name: "Сакура",
    color: "Фиолетовый",
    category: "food",
    type: "Японская коллекция",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 5,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Оригинальный, насыщенный, умеренно сладкий",
    img: "sakura.webp",
    price: "—",
    advantages: ["Новинка"],
    patent: false
  },
  {
    id: 304,
    name: "Санрайз",
    color: "Белый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 3,
    droughtResistance: 3,
    productivity: "Средняя",
    storage: "Средняя",
    tasteProfile: "Нежный, сбалансированный, умеренно сладкий",
    img: "sanrayz.webp",
    price: "—",
    advantages: ["Авторский", "Новинка"],
    patent: false
  },
  {
    id: 305,
    name: "Цветик семицветик",
    color: "Фиолетовый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 3,
    advantages: ["Авторский", "Новинка"],
    patent: false
  },
  {
    id: 306,
    name: "Эрато пурпурный",
    color: "Фиолетовый",
    category: "food",
    type: "Японская коллекция",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 3,
    advantages: ["Новинка"],
    patent: false
  },
  {
    id: 307,
    name: "Эластик",
    color: "Фиолетовый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 7,
    advantages: ["Авторский", "Новинка"],
    patent: false
  },
  {
    id: 308,
    name: "Ночная фурия",
    color: "Фиолетовый",
    category: "food",
    type: "Авторский",
    term: "Поздний (110+)",
    termDays: {min: 110, max: 140},
    sweetness: 5,
    advantages: ["Авторский", "Новинка"],
    patent: false
  }
];